export PWD="$HOME/win-dotfiles/shell"

[ -f $PWD/aliases.zsh ] && source $PWD/aliases.zsh
[ -f $PWD/common.zsh ] && source $PWD/common.zsh
[ -f $PWD/secrets.zsh ] && source $PWD/secrets.zsh
[ -f $PWD/functions.zsh ] && source $PWD/functions.zsh
[ -f $ZSH/oh-my-zsh.sh ] && source $ZSH/oh-my-zsh.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Keybinds
bindkey -s '^O' 'ranger-cd\n'
bindkey -s '^P' 'my_fzf\n'

# Init plugins
eval "$(zoxide init zsh)"
