setopt auto_cd

export SRC="$HOME/.config/win-dotfiles/shell"

[ -f $SRC/common.zsh ] && source $SRC/common.zsh
[ -f $SRC/secrets.zsh ] && source $SRC/secrets.zsh
[ -f $SRC/functions.zsh ] && source $SRC/functions.zsh

if [[ -n $MS_OH_MY_ZSH ]]; then
  [ -f $SRC/oh-my-zsh.zsh ] && source $SRC/oh-my-zsh.zsh
  [ -f $ZSH/oh-my-zsh.sh ] && source $ZSH/oh-my-zsh.sh
fi

if [[ -f ~/.fzf.zsh ]]; then
 export FZF_DEFAULT_OPTS='--preview "bat --color=always --style=numbers --line-range=:500 {}"'
 source ~/.fzf.zsh
fi

[ -f $SRC/aliases.zsh ] && source $SRC/aliases.zsh

# Keybinds
bindkey -v

bindkey -s '^O' 'ranger-cd\n'
bindkey -s '^P' 'my_fzf\n'

# Init plugins

if [[ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
  source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
else
  echo "zsh-syntax-highlighting not found"
  echo "https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md"
fi

if (( $+commands[zoxide] )); then
  eval "$(zoxide init zsh --cmd cd)"
fi

if [[ -n $MS_OH_MY_POSH ]]; then
  eval "$(oh-my-posh init zsh --config $HOME/.config/win-dotfiles/posh/M365Princess.omp.json)"
  source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

export GPG_TTY="$(tty)"


if [[ -n $MS_WSL_YUBIKEY ]]; then
  export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
  gpgconf --launch gpg-agent

  2>/dev/null 1>&2 gpgagentr
fi

autoload -U +X bashcompinit && bashcompinit

if [[ -f /usr/bin/terraform ]]; then
  complete -o nospace -C /usr/bin/terraform terraform
fi

if (( $+commands[go] )); then
  export GOPATH=$HOME/go
  export PATH=$PATH:$GOPATH/bin
fi

if (( $+commands[tmux] )); then
  if (( $+TMUX )); then
    # Do nothing when creating a new window
  else
    if tmux has-session -t $(whoami) 2>/dev/null; then
      tmux attach -t $(whoami)
    else
      tmux new -s $(whoami)
    fi
  fi
fi

if (( $+commands[java] )); then
  export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
  export ANDROID_HOME="/opt/android"

  export PATH=$PATH:$ANDROID_HOME/cmdline-tools/tools/bin
  export PATH=$PATH:$ANDROID_HOME/platform-tools
  export PATH=$PATH:$ANDROID_HOME/emulator

  export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib64/qt5/plugins/platforms
fi
