#!/usr/bin/python3

import shutil
import sys
import subprocess
import json


def cmd(command):
    return subprocess.run(
        command,
        shell=True,
        executable='/bin/zsh',
        encoding='utf-8',
        stdout=subprocess.PIPE)


def main():
    print('🔑 Loading secrets from Bitwarden')
    # Check if `bw` binary is installed
    if not shutil.which('bw'):
        print('🔴 Bitwarden CLI is not installed')
        sys.exit(1)

    # Unlock Bitwarden vault
    unlock = cmd(f"bw unlock --raw")

    if unlock.returncode != 0:
        print('🚨 Bitwarden vault unlock failed')
        sys.exit(1)

    print('🔓 Bitwarden vault unlocked')
    bw_session_key = unlock.stdout

    print('🔃 Syncing Bitwarden vault')
    cmd(f"bw sync --session {bw_session_key}")

    # Create a folder ~/.secrets if not exists
    cmd(f"mkdir -p ~/.secrets")

    # Load secrets from deps.json
    with open('deps.json') as f:
        deps = json.load(f)
        secrets = deps['secrets']

    for secret in secrets:
        load_secret(secret, bw_session_key)


def load_secret(secret_name, session_key):
    s = cmd(
        f"bw get notes {secret_name} --session {session_key} > ~/.secrets/{secret_name}")

    print(f'{secret_name} loaded ✅')
    return s.stdout


if __name__ == "__main__":
    main()
